sudo: false
dist: trusty
language: python
python:
  - "2.7.13"
  - "3.6.1"
  - "nightly"  # currently points to 3.7-dev
before_install:
  - pip install flake8
  - flake8 . --exit-zero --select=E901,E999
install:
  - pip install numpy
script: py.test -s
